INSERT INTO Product (prodName, prodPicNameSmall, prodPicNameLarge, prodDescripShort, prodDescripLong, prodPrice, prodQuantity) 
VALUES ('HIVE Active Heating Thermostat', 'hivesmall.jpg', 'hivebig.jpg', 'Hive Active Heating connects you AND your heating system via an app
ON your mobile device to give you convenient control over operating times
FROM wherever you are.', '
WITH an all-new wall-mounted thermostat control unit, Hive Active Heating looks great AND can reduce the heating bills IN any home.
WITH control
FROM your mobile, laptop or tablet, you\'ll never need to heat an empty home again. Up to six heating events can be scheduled throughout the day, so you can wake up IN comfort, cut the heating while the house is empty AND return to a comfortable home after a long day at work. ', 145.00, 35);
VALUES ('A microwave oven', 'microwavesmall.jpg', 'microwavebig.jpg', 'An electric oven that heats and cooks food by exposing it to electromagnetic radiation in the microwave frequency range.[1] This induces polar molecules in the food to rotate and produce thermal energy in a process known as dielectric heating. Microwave ovens heat foods quickly and efficiently because excitation is fairly uniform in the outer 25–38 mm (1–1.5 inches) of a homogeneous, high-water-content food item.', '
The development of the cavity magnetron in the UK made possible the production of electromagnetic waves of a small enough wavelength (microwaves). American engineer Percy Spencer is generally credited with inventing the modern microwave oven after World War II from radar technology developed during the war. Named the "Radarange", it was first sold in 1946.', 145.00, 35);
VALUES ('Airfrier', 'airfriersmall.jpg', 'airfrierbig.jpg', 'Air fryers circulate hot air to cook food that would otherwise be submerged in oil. The air fryers cooking chamber radiates heat from a heating element near the food, and a fan circulates hot air.', 
'The original Philips Airfryer used radiant heat from a heating element just above the food and convection heat from a strong air stream flowing upwards through the open bottom of the food chamber, delivering heat from all sides, with a small volume of hot air forced to pass from the heater surface and over the food, with no idle air circulating as in a convection oven. A shaped guide directed the airflow over the bottom of the food. The technique was patented as Rapid Air technology.', 145.00, 35);
VALUES ('CoffeeMaker', 'coffeemakersmall.jpg', 'coffeemakerbig.jpg', 'A coffee maker is an electric countertop appliance that brews hot coffee automatically. It consists of a hot plate, a carafe or glass coffee pot, filter basket, and water reservoir.', 
'A coffee maker is a very simple, low-tech, yet efficient machine. A heating element circles the hot plate at the bottom of the maker. Wrapped in this heating element is a hollow aluminum tube. When water is added to the reservoir, a small hole in the bottom of the container feeds a plastic hose that leads down to one end of the aluminum tube. Once the coffee pot is switched on, the heating element gets hot very quickly. Sensors cycle the element on and off to keep it 195-205 degrees Fahrenheit (90-96 Celsius). Water sitting in the aluminum tube boils and the turbulence creates bubbles that rise though the opposite end of the tube, traveling up an exit hose (making room for more water to enter the heating element). Hot water riding on these rising bubbles creates upward lift that carries a small stream of boiling water to the top of the coffee maker.', 145.00, 35);
